;;;; t/registry-test.lisp
(in-package #:cl-codec-kit/test)

(describe
  "the encoding registry"
  (it "lists every canonical encoding registered by this library's encoding files"
    (let ((names (list-character-encodings)))
      (dolist (expected '(:utf-8 :utf-16 :utf-16be :utf-16le :utf-32 :utf-32be :utf-32le
                          :ucs-2 :ucs-2be :ucs-2le :ascii :iso-8859-1))
        (expect (member expected names) :to-be-truthy))))

  (it "FIND-CHARACTER-ENCODING resolves both canonical names and aliases to the same object"
    (expect (find-character-encoding :iso-8859-1) :to-be (find-character-encoding :latin-1)))

  (it "signals UNSUPPORTED-ENCODING for an unregistered designator"
    (signals unsupported-encoding (find-character-encoding :not-a-real-encoding)))

  (it "*DEFAULT-ENCODING* is :UTF-8 and is honored when :ENCODING is omitted"
    (expect *default-encoding* :to-be :utf-8)
    (expect (octets-to-string (string-to-octets "café")) :to-equal "café")))

(describe
  "CHARACTER-ENCODING-DEFAULT-REPLACEMENT, per encoding"
  ;; This table is transcribed from babel's source, not from its
  ;; documentation, and deliberately not from its ENC-DEFAULT-REPLACEMENT
  ;; slot: that slot is exported (packages.lisp:48) and initialized
  ;; (encodings.lisp:70-71, enc-unicode.lisp:54 and elsewhere), but no babel
  ;; code path ever reads it back, so it does not describe what babel does.
  ;;
  ;; What babel actually substitutes is whichever code point a codec hands
  ;; to DECODING-ERROR/ENCODING-ERROR (encodings.lisp:497, :522):
  ;;
  ;;   Unicode family  +REPL+ = #xFFFD           enc-unicode.lisp:33, used at
  ;;                                             :187 :193 :629 :633 :757 :777
  ;;   single-octet    +DEFAULT-SUBSTITUTION-    encodings.lisp:370, reached
  ;;                   CODE-POINT+ = #x1A        from :405 and :430, the
  ;;                                             HANDLE-ERROR of DEFINE-
  ;;                                             UNIBYTE-ENCODER/-DECODER
  ;;                                             that :ASCII (enc-ascii.lisp)
  ;;                                             and :ISO-8859-1
  ;;                                             (enc-iso-8859.lisp:47,:52)
  ;;                                             are both built from
  ;;
  ;; babel cannot be loaded here to check this differentially -- it is an
  ;; external dependency this library exists to remove, and DEPENDENCY_POLICY
  ;; forbids it even as a test dependency -- so the citation above is the
  ;; evidence and this test is what keeps the transcription honest.
  ;; One named case per encoding, via IT-EACH, rather than a DOLIST that would
  ;; only ever report the first mismatch and never say which encoding it was.
  (it-each ((:utf-8 #xFFFD) (:utf-16 #xFFFD) (:utf-16be #xFFFD) (:utf-16le #xFFFD)
            (:utf-32 #xFFFD) (:utf-32be #xFFFD) (:utf-32le #xFFFD)
            (:ucs-2 #xFFFD) (:ucs-2be #xFFFD) (:ucs-2le #xFFFD)
            (:ascii #x1A) (:iso-8859-1 #x1A))
      "~A's default replacement is U+~4,'0X"
      (name expected-code)
    (expect (char-code (character-encoding-default-replacement (find-character-encoding name)))
            :to-be expected-code))

  (it "is U+001A (SUB), not U+FFFD, because the single-octet encodings cannot represent U+FFFD"
    ;; Not merely a convention: the alternative does not encode at all.
    (dolist (name '(:ascii :iso-8859-1))
      (signals unencodable-character
          (string-to-octets (string #\REPLACEMENT_CHARACTER) :encoding name))))

  (it "is set for every registered encoding, so no caller can reach an unset default"
    (dolist (name (list-character-encodings))
      (expect (characterp (character-encoding-default-replacement
                           (find-character-encoding name)))
              :to-be-truthy)))

  (it "is itself encodable in its own encoding, for every registered encoding"
    ;; %LENIENT-ENCODE (api.lisp) propagates UNENCODABLE-CHARACTER rather than
    ;; looping when REPLACEMENT cannot be encoded. That escape hatch is for
    ;; explicit :REPLACEMENT arguments; the default must never trip it.
    (dolist (name (list-character-encodings))
      (let ((replacement (character-encoding-default-replacement
                          (find-character-encoding name))))
        (expect (plusp (length (string-to-octets (string replacement) :encoding name)))
                :to-be-truthy)))))

(describe
  "every registered encoding's strict decoder"
  ;; Every FOO-test.lisp exercises a handful of hand-picked invalid byte
  ;; sequences by name (a stray continuation byte, an overlong sequence, and
  ;; so on). This checks the much stronger, encoding-generic invariant behind
  ;; all of them at once: OCTETS-TO-STRING either decodes ARBITRARY bytes or
  ;; signals a DECODE-ERROR subtype, and never a raw, unclassified Lisp
  ;; error, for any of the 300 generated byte sequences per trial across
  ;; every registered encoding.
  (it-fuzz "OCTETS-TO-STRING never signals outside the DECODE-ERROR hierarchy"
      ((bytes (gen-octets :min-length 0 :max-length 12))
       (encoding (gen-member (list-character-encodings))))
      (:trials 300)
    (handler-case (octets-to-string bytes :encoding encoding)
      (decode-error () nil))))
